version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "yearly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "yearly"
