services:
# vault
  vault:
    container_name: vault
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - default
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
#vault add secrets on startup
  vault-prepopulate:
      image: alpine/curl
      depends_on:
        vault:
          condition: service_started
      volumes:
        - ./init-vault.sh:/usr/local/bin/init-vault.sh
      command: [ "sh", "-c", "apk add --no-cache openssl && /usr/local/bin/init-vault.sh" ]
      networks:
        - default
#postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d testdb" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - default
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - default
# elastic + kibana = love
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - logger.level=ERROR
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    depends_on:
      - main_app
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.0
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/app/logs
    entrypoint: "filebeat -e -strict.perms=false"
    depends_on:
      main_app:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - default

# main app
  main_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      VAULT_HOST: vault
    working_dir: /app
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      vault-prepopulate:
        condition: service_completed_successfully
      postgres:
        condition: service_started

# networks, volumes etc.
networks:
  default:
    name: externalprojectsusersnetwork
    driver: bridge

volumes:
  postgres_data:
  esdata:

