filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/app.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message

logging.level: warning
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"
