spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testdb
    username: user
    password: password
  liquibase:
    url: jdbc:postgresql://localhost:5432/testdb
    user: user
    password: password
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    org.springframework: DEBUG    # Логи для Spring R2DBC
    io.r2dbc.postgresql: DEBUG          # Логи для драйвера PostgreSQL
    org.springframework.data.r2dbc: DEBUG # Логи для Spring Data R2DBC
    reactor: DEBUG                      # Логи для реактивного фреймворка Reactor
    org.springframework.transaction: TRACE # Логи для транзакций (если нужно)