spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testdb
    username: user
    password: password
  liquibase:
    url: jdbc:postgresql://localhost:5432/testdb
    user: user
    password: password
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.cache.interceptor.CacheInterceptor: TRACE