spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/testdb
    username: user
    password: password
  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/testdb
    user: user
    password: password
  cloud:
    vault:
      uri: http://${VAULT_HOST:localhost}:8200
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: jwt-signing
  config:
    import: optional:vault://
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true


logging:
  level:
    com.krysenko4sky: DEBUG
